apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: pia-survey
  namespace: pia

spec:
  image: {{image}}

  liveness:
    path: /internal/isalive
    port: 8080
    initialDelay: 20
    timeout: 60
  readiness:
    path: /internal/isready
    port: 8080
    initialDelay: 20
    timeout: 60

  azure:
    application:
      enabled: true
      allowAllUsers: false

  kafka:
    pool: {{kafkaPool}}

  gcp:
    sqlInstances:
      - type: POSTGRES_17
        tier: {{dbTier}}
        databases:
          - name: pia-survey-db

  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
    logging:
      destinations:
        - id: elastic
        - id: loki
